version: '3.8'
services:
  go_app:
    build:
      context: .
    ports:
      - "50051:50051"
      - "4242:4242"

    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    volumes:
      - ./redisdata:/data
    ports:
      - "6379:6379"
